OpenFunction/builder

cmd/go/of_functions_framework/main.go
cmd/go/of_functions_framework/template.go

Signed-off-by: laminar <fangtian@kubesphere.io>

Update go/of_functions_framework to latest

---

README.md
cmd/go/of_functions_framework/main.go
cmd/go/of_functions_framework/template.go

1. Update template of main function
2. Update functions-framework-go version to `v0.0.0-20210628081257-4137e46a99a6`
3. Update support list

Update of_functions_framework to latest

---

README.md

Fix some link errors in README.md

Fix some link errors in README.md

---

pkg/golang/golang.go

Added a judgment that returns true if the current buildpacks is OpenFunction Functions Framework, because OpenFunction Functions Framework buildpacks itself requires that the version of go is not less than 1.15.
```go
// IsOpenFunctionFunctionsFramework returns true if the buildpacks is OpenFunction Functions Framework.
// Because the OpenFunction functions framework requires the go version to be at least 1.15.
func IsOpenFunctionFunctionsFramework(ctx *gcp.Context) bool {
return ctx.BuildpackID() == OpenFunctionFunctionsFrameworkID
}
```
Signed-off-by: laminar <fangtian@kubesphere.io>

Fix: Enables the OpenFunction functions framework to use the FUNC_GOPROXY environment variable.

---

builders/go115/README.md
builders/go116/README.md
cmd/go/of_functions_framework/buildpack.toml
cmd/go/of_functions_framework/main.go

Upgrade of_functions_framework buildpacks to v0.1.0

---

builders/go115/README.md
builders/go116/README.md
cmd/go/of_functions_framework/main.go

update functions-framework-go to v0.1.1

---

builders/go116/README.md
builders/go116/stack/run.busybox.parent.Dockerfile
builders/go116/stack/run.parent.Dockerfile

Use distroless as base run image and change user of run image to nonroot

---

cmd/go/of_functions_framework/main.go

Change functions-framework buildpack layer from Launch to Build and Cache

---

WORKSPACE
builders/base/acceptance/go_test.go
builders/testdata/generic/go/simple_gomod_vendor/go.mod
go.mod
pkg/golang/golang_test.go
tools/cloudbuild/Dockerfile

Upgrade bazel rules_go to v0.29.0 & upgrade go to 1.16.13

---

cmd/go/of_functions_framework/main.go

chore: adjust the indent

---

builders/node16/README.md

Adjust readme for nodejs builder

---

cmd/nodejs/functions_framework/converter/without-framework/package-lock.json
cmd/nodejs/functions_framework/converter/without-framework/package.json

use openfunction's own functions-framework

---

builders/node16/README.md
cmd/nodejs/functions_framework/converter/without-framework/README.md
cmd/nodejs/functions_framework/converter/without-framework/package-lock.json
cmd/nodejs/functions_framework/converter/without-framework/package.json

Update nodejs functions-framework to 0.3.6

---

cmd/go/of_functions_framework/main.go
pkg/env/env.go

Add functions framework version env var

---

cmd/go/of_functions_framework/main.go
cmd/go/of_functions_framework/template.go

update functions-framework-go to v0.2.0 in openfunction/builder-go:v2

---

cmd/go/of_functions_framework/buildpack.toml
cmd/go/of_functions_framework/main.go

update functions-framework-go to v0.2.1 in openfunction/builder-go:v2

---

cmd/nodejs/functions_framework/converter/without-framework/package-lock.json
cmd/nodejs/functions_framework/converter/without-framework/package.json
cmd/nodejs/functions_framework/main.go

upgrade nodejs functions-framework to v0.4.0

---

builders/node16/README.md
cmd/nodejs/functions_framework/converter/without-framework/package-lock.json
cmd/nodejs/functions_framework/converter/without-framework/package.json

upgrade nodejs functions-framework to 0.4.1

---

cmd/nodejs/functions_framework/converter/without-framework/README.md
cmd/nodejs/functions_framework/converter/without-framework/package-lock.json
cmd/nodejs/functions_framework/converter/without-framework/package.json

Signed-off-by: Haili Zhang <haili.zhang@outlook.com>

chore: bump node functions framework to 0.5.0

---

builders/BUILD.bazel
builders/go117/BUILD.bazel
builders/go117/README.md
builders/go117/acceptance/BUILD.bazel
builders/go117/acceptance/acceptance.go
builders/go117/acceptance/config.yaml
builders/go117/acceptance/go_fn_test.go
builders/go117/builder.toml
builders/go117/stack/BUILD.bazel
builders/go117/stack/build.Dockerfile
builders/go117/stack/build.sh
builders/go117/stack/parent.Dockerfile
builders/go117/stack/run.Dockerfile
builders/go117/stack/run.busybox.Dockerfile
builders/go117/stack/run.distroless.Dockerfile
cmd/config/entrypoint/buildpack.toml
cmd/go/build/buildpack.toml
cmd/go/clear_source/buildpack.toml
cmd/go/of_functions_framework/buildpack.toml
cmd/go/of_functions_framework/main.go
cmd/utils/label/buildpack.toml

Signed-off-by: wrongerror <wangyifei@kubesphere.io>

add go117 builder & bump ff-go to v0.4.0

---

builders/go117/README.md

Signed-off-by: wrongerror <wangyifei@kubesphere.io>

modify go117 README.md
